### ISSUE TITLE
Import is causing my tests to fail.

### ISSUE THREAD

**Issue by akrigline** [renato-bohler/redux-form-input-masks#14]
### What are you reporting?

- [X] Bug
- [ ] Feature request
- [ ] Code refactor
- [ ] Continuous Integration (CI) improvement
- [ ] Changes in documentation (docs)
- [ ] Other (describe)

### What is the current behavior?
Importing this library and running jest tests is causing an error:
```bash
node_modules/redux-form-input-masks/src/createNumberMask.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { escapeRegExp, countOcurrences } from './utils';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import
```

### What is the expected behavior?
Library should not cause tests to fail.

### Sandbox Link
I believe the error is the same as when it is loaded here:
https://npm.runkit.com/redux-form-input-masks

### Other information
It seems that this is caused because the library relies on itself being used somewhere where it will be transpiled down, rather than serving a dist of pre-transpiled files? As such the `import` is causing issues in environments where `import` isn't valid.

**Comment by renato-bohler** [comment]
Hey there!

Thanks for taking your time and reporting this. I can give it a look in this upcoming week.

Please note though that this project is still under development and it is not ready for use in production.

**Comment by renato-bohler** [comment]
I've worked on this issue today. The project is being transpiled now.

The problem reproduced at both [RunKit](https://npm.runkit.com/redux-form-input-masks) and Jest tests aren't happening anymore.

Can you please try again using *redux-form-input-masks@0.3.12* @akrigline ?

**Comment by renato-bohler** [comment]
If it still happens on versions greater than 0.3.12, please reopen this issue.
