### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by Kenjirou** [renato-bohler/redux-form-input-masks#22]
### What are you reporting?

*Bug*

### What is the current behavior?

*When I try to start my app with this package installed I see the error message*

### What is the expected behavior?

*I can start my app as usual*

### What's your environment?

> Version: 1.0.0
> OS: Ubuntu Linux 17.10 64-bit
> Browser: Chrome 65 (64 bits)
> Node version: 8.9.3

**Comment by renato-bohler** [comment]
I have had this error once at codesandbox.io, but it simply disappeared after some time.

I'll take a look later today.

**Comment by renato-bohler** [comment]
@Kenjirou can you please try again? If the error persists, reopen this issue.

Thanks for your report!

**Comment by Kenjirou** [comment]
@renato-bohler yeah, now it works!
Thank you for your work)
