### ISSUE TITLE
When using `createTextMask` getting `TypeError: Object(...) is not a function`

### ISSUE THREAD

**Issue by polinom** [renato-bohler/redux-form-input-masks#24]
### When using `createTextMask` getting `TypeError: Object(...) is not a function` 

* [ ] Bug

### What is the current behavior?

When import and using `createNumberMask`everything works as expected. However, when using `createTextMask` it errors out like this:

![](https://preview.ibb.co/i7x7pc/Screen_Shot_2018_03_13_at_11_13_37_PM.png)

### What is the expected behavior?

I expect it to work like described in documentation and demonstrated on demo.

**Comment by renato-bohler** [comment]
I still couldn't reproduce it on **^1.0.0**.

@polinom if the problem is really occuring on v1, please confirm and I'll keep trying to reproduce it.

Thanks

**Comment by polinom** [comment]
I'm sorry @renato-bohler for late response , It was indeed lower than **1.0.0** problem.
