### ISSUE TITLE
The default value of the createNumberMask is 0 and can not be changed

### ISSUE THREAD

**Issue by shchouch** [renato-bohler/redux-form-input-masks#29]
### What are you reporting?

* [ ] Bug
* [x] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

When the createNumberMask mask applied to a Field this Field renders with '0' by default. 

### What is the expected behavior?

Is it possible to add some additional property to the object that is passed to the createNumberMask that will set the initial or default value or just leave the input blank? So that by default there would be no '0's or any other numbers. Just empty input.

### What's your environment?

> Version: 1.0.1
> OS: Linux Ubuntu 17.10  64-bit
> Browser: Chrome 65 (64 bits)
> Node version: 9.2.0

**Comment by renato-bohler** [comment]
Hey! Thanks for taking your time and submitting this feature request.

So... this feature is on the roadmap, but I'm currently lacking time to work on the project.

As soon as I have the time, I'll prioritize the existing issues and then I'll work on this feature.

**Comment by renato-bohler** [comment]
Closed by #30

**Comment by hasan-aliyev** [comment]
@renato-bohler can you please have a look this code sand box link?
[Codesandbox](https://codesandbox.io/s/rqvto?file=/CreateNumberMask.jsx)
All I want is to avoid having 0 on load

**Comment by renato-bohler** [comment]
Well that seems like a better solution hehe
