### ISSUE TITLE
Selecting an entire value and hitting delete should delete the selected value

### ISSUE THREAD

**Issue by scottmcpherson** [renato-bohler/redux-form-input-masks#43]
### What are you reporting?
Currently, the only way to delete the entire value is by hitting delete once for each digit. It would be a better UX to be able to select the entire value and delete it by hitting delete once.

* [X] Bug
* [X] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

<img width="377" alt="raisal - broker 2018-06-21 14-51-51" src="https://user-images.githubusercontent.com/2382172/41739436-09fc63d8-7563-11e8-881d-b6cad2e33ac7.png">

**Comment by renato-bohler** [comment]
I totally agree. I'll give it a try in the next few weeks.

**Comment by scottmcpherson** [comment]
Let me know if I can help! Happy to submit a PR

**Comment by scottmcpherson** [comment]
@renato-bohler I was able to resolve this but wanted to check with you before modified the test to get them to pass.

To get this to work, part of what I did was removed this block:
https://github.com/renato-bohler/redux-form-input-masks/blob/master/src/createNumberMask.js#L60-L66

What is the purpose of this block? With it removed, it still prevents the modification of suffixes and prefixes.

**Comment by renato-bohler** [comment]
Yes, tests will have to be updated.

I would have to check, but I suspect that without this block, messing only with the prefix and suffix would clear the input, and in this case the input field should just not be updated.
