### ISSUE TITLE
Cursor (caret) jumps to end of input, then returns to correct position

### ISSUE THREAD

**Issue by dubert** [renato-bohler/redux-form-input-masks#47]
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

As the user is typing, the caret jumps to end, then returns to the correct position. 
![phone_number](https://user-images.githubusercontent.com/1843672/42700185-fb8830d6-8690-11e8-91db-79ed350552c4.gif)

### What is the expected behavior?

The user should just be able to type normally without needing to reset the caret position.

### What's your environment?

> Version: 1.1.5
> OS: Mac OS X 10.11
> Browser: Chrome 67
> Node version: 8.9.2

### Other information

I downloaded the repo, and started messing around in the code to see if I could figure it out. It seems to be related to this React issue: https://github.com/facebook/react/issues/955

I will continue investigating and see if I can find a fix.

**Comment by dubert** [comment]
**Update:** From what I can tell, the primary culprit is Redux-form, because `format()/normalize()` pretty much clobbers everything.
Related issues:
https://github.com/erikras/redux-form/issues/2049
https://github.com/erikras/redux-form/issues/3253
https://github.com/erikras/redux-form/issues/3306

**Comment by renato-bohler** [comment]
Yeah, I've tried my best to fix this but it was really beyond me.

The only way to avoid this behaviour is setting the `guide` option to `false`. I'm also thinking in changing `guide`'s default value to `false` in v2.0.0.

I'm closing this by now. If you have any other suggestion on this topic, feel free to reopen.

Thanks for reporting!
