### ISSUE TITLE
Empty mask overrides placeholder

### ISSUE THREAD

**Issue by TimMeade** [renato-bohler/redux-form-input-masks#48]
### What are you reporting?

* [ ] Bug
* [x] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?
I think this may fall under feature request, but maybe I'm missing something.

If there is a placeholder for the Field, you are over riding it from init with the mask .   I believe this is incorrect behaviour as the font color etc is for data in field not placeholder.   This causes the look of the empty form to be unacceptable.

Mask overrides the placeholder causing dark text to be in one input field only on blank form.

### What is the expected behavior?

Allow placeholder on empty data,   Bring Mask to front when actual data in Field.

Unacceptable look/feel on empty form.

**Comment by TimMeade** [comment]
![screenshot 2018-07-14 07 29 22](https://user-images.githubusercontent.com/1386476/42723977-a53c0804-8737-11e8-9d16-35927970e9d8.png)
![screenshot 2018-07-14 07 30 03](https://user-images.githubusercontent.com/1386476/42723984-c17a093a-8737-11e8-9b1f-46ac5592cf89.png)

**Comment by sjarvie** [comment]
+1 on this.

**Comment by renato-bohler** [comment]
@sjarvie oh I see. So, to achieve what I've done in the GIF you see on the README I've used the `TextField` from `redux-form-material-ui@5` (`material-ui@1` wrappers) with the `placeholder` prop set to `AAAA - (99)99` with the following mask applied to it. Something along those lines:

```jsx
import { Field } from 'redux-form';
import { TextField } from 'redux-form-material-ui';
import { createTextMask } from 'redux-form-input-masks';

// (...)

<Field
    component={TextField}
    name="myField"
    placeholder="AAAA - (99)99"
    {...createTextMask({
        pattern: 'AAAA - (99)99',
        guide: false,
    })}
/>
```

**Comment by renato-bohler** [comment]
I'll be closing this one then.

Feel free to reopen it @TimMeade
