### ISSUE TITLE
TextInputMask incorrectly overrides placeholder with single paranthesis when mask starts with open parenthesis

### ISSUE THREAD

**Issue by sjarvie** [renato-bohler/redux-form-input-masks#53]
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

When a text input mask starts with an open parenthesis, the placeholder string of Input(not placeholder character of mask), is overridden to a single open parenthesis.

Example:

```
import { Field } from 'redux-form';
import { TextField } from 'redux-form-material-ui';
import { createTextMask } from 'redux-form-input-masks';

// (...)

<Field
    component={TextField}
    name="myField"
    placeholder="000 000-0000"
    {...createTextMask({
        pattern: '999 999-9999',
        guide: false,
    })}
/>
```

produces

<img width="464" alt="screen shot 2018-07-23 at 9 28 46 am" src="https://user-images.githubusercontent.com/4016627/43089976-f94fd2c0-8e5a-11e8-91c0-cc99feaaee05.png">

```
import { Field } from 'redux-form';
import { TextField } from 'redux-form-material-ui';
import { createTextMask } from 'redux-form-input-masks';

// (...)

<Field
    component={TextField}
    name="myField"
    placeholder="(000) 000-0000"
    {...createTextMask({
        pattern: '(999) 999-9999',
        guide: false,
    })}
/>
```

produces

<img width="467" alt="screen shot 2018-07-23 at 9 29 34 am" src="https://user-images.githubusercontent.com/4016627/43089971-f435b4d0-8e5a-11e8-8e36-b5b7997b9966.png">

Video below:

https://www.useloom.com/share/d0c13861b5ca4aac8c5429c46afeda31

### What is the expected behavior?

The placeholder string should show as `(000) 000-0000`

### Sandbox Link

https://codesandbox.io/s/oq5w4ylopy

### Other information

My best guess is that this is caused by a regex run on component declaration.

Related: https://github.com/renato-bohler/redux-form-input-masks/issues/48

**Comment by renato-bohler** [comment]
The current behavior is how I thought it was supposed to be. But I now see that this alternative behavior can be pretty useful.

My purpose is to make a new option for `createTextMask` called `allowEmpty`, that when set to true, will not show any mask character if the input hasn't been filled (just like the `allowEmpty` option that already exists for `createNumberMask`).

That would solve this problem, right?

**Comment by sjarvie** [comment]
`allowEmpty` should solve this case, yes. Once the user starts typing, the mask should apply.

Thank you for taking a look here.

**Comment by sjarvie** [comment]
Thank you!
