### ISSUE TITLE
Does not work with typescript

### ISSUE THREAD

**Issue by yardz** [renato-bohler/redux-form-input-masks#57]
### What are you reporting?
* [ ] Bug
* [ x ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ x ] Other (describe)

### What is the current behavior?

Does not work with typescript... I tried to create an @Types file but I could not. (I'm new to Typescrypt)

### What is the expected behavior?

Create an pakege @types/redux-form-input-masks

### Other information

Apparently your package is very good, but I could not use it because I'm in a project with Typescript
I believe that others are having the same difficulty.

**Comment by renato-bohler** [comment]
Sorry for the late response.

I was able to do a quick test and `redux-form-input-masks` apparently works with TypeScript without any problems. [Here's the link to the sandbox](https://codesandbox.io/s/2x6kr0807n).

Is there anything different from what you're doing?
