### ISSUE TITLE
CodeSandbox.io Demo is not working.

### ISSUE THREAD

**Issue by dzienisz** [renato-bohler/redux-form-input-masks#58]
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [x] Other (describe)

### What is the current behavior?

CodeSandbox.io Demo is not working.
https://codesandbox.io/s/k0op1kwywr

**Comment by renato-bohler** [comment]
Thanks for reporting it, I'll investigate.

**Comment by renato-bohler** [comment]
Should be all right now. If it still happens, please reopen.
