### ISSUE TITLE
Is it possible to hide underscores in text input mask?

### ISSUE THREAD

**Issue by dzienisz** [renato-bohler/redux-form-input-masks#59]
### What are you reporting?

* [ ] Bug
* [x] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

![zrzut ekranu 2018-10-10 o 17 27 31](https://user-images.githubusercontent.com/3521624/46747540-e0f17b80-ccb1-11e8-8870-734adbf13eba.png)

### What is the expected behavior?

I have mu custom styled <Field> and I would like to get rid of underscores. Is it possible?

**Comment by renato-bohler** [comment]
Hey there. Yes, this is possible. There's two ways you could achieve it:

**1. Change the `placeholder` option on the `createTextMask`, setting it to a blank space. Example:**

```jsx
import { createTextMask } from 'redux-form-input-masks';

const myCustomTextMask = createTextMask({
    pattern: '(999) 999-9999',
    placeholder: ' ',
});
```

**2. Hide all the guide by setting the `guide` option to false. Example:**

```jsx
const myCustomTextMask = createTextMask({
    pattern: '(999) 999-9999',
    guide: false,
});
```

You can play with the available options (and get the resulting code) on the [text mask page of the documentation](https://renato-bohler.github.io/redux-form-input-masks/#/text-mask) (scroll down to the **Build your own** section).

I'm closing this for now, but if you still have any questions, feel free to reopen.

**Comment by dzienisz** [comment]
It's working! but...

![zrzut ekranu 2018-10-11 o 10 25 41](https://user-images.githubusercontent.com/3521624/46791058-9703a680-cd40-11e8-9f37-b76ddd718211.png)
![zrzut ekranu 2018-10-11 o 10 25 48](https://user-images.githubusercontent.com/3521624/46791059-9703a680-cd40-11e8-83b7-fa1a252221b9.png)
![zrzut ekranu 2018-10-11 o 10 28 15](https://user-images.githubusercontent.com/3521624/46791061-979c3d00-cd40-11e8-9831-8b9a281ef79f.png)

Is it possible to preserve letter spacing in placeholder?

**Comment by renato-bohler** [comment]
The space character is thinner than the digits, is that what you mean?

The `placeholder` option is limited to 1 character... so if that's the problem, I can't see a way of adjusting the width other than selecting a monospace font to display on the input.
