### ISSUE TITLE
select() Not working

### ISSUE THREAD

**Issue by juniordesenv** [renato-bohler/redux-form-input-masks#61]
i'm trying  to focus on an input with predifined value with .select(), but the cursor focuses on the input without the selection

**Comment by juniordesenv** [comment]
I found a way around this, but I think it would be interesting to include a fix for that. I put it to shoot the focus and with a timeout shoot the select..

document.getElementById('#field').focus()
setTimeout(() => { document.getElementById('#field').select() }, 10)

**Comment by renato-bohler** [comment]
Hmm, I don't think this is under this library responsibility. This is more likely a problem with the field component that you are using.
