### ISSUE TITLE
Entering large number eventually doesn't reflect input

### ISSUE THREAD

**Issue by druchoy** [renato-bohler/redux-form-input-masks#63]
### What are you reporting?
Number mask

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

As I try to input a large number, after about 10 characters, the field begins to no longer reflect my input.
- As I enter 0-9 in sequence, after the 10th input char, i only get 0's.
- As I enter 9's, my field eventually gets replaced with 100000000...

### What is the expected behavior?

Expect input to be reflected in input field.

### Sandbox Link

Able to replicate on homepage - just put a bunch of 9's:
https://renato-bohler.github.io/redux-form-input-masks/#/number-mask

Can simulate in default sandbox link:
https://codesandbox.io/s/v0rj4p6y0

### Other information

![screen shot 2019-01-14 at 2 26 52 pm](https://user-images.githubusercontent.com/346409/51145623-42713b00-1809-11e9-992b-70bad6088d77.png)

**Comment by renato-bohler** [comment]
Hmm, this is a JavaScript precision issue. See this [stackoverflow question](https://stackoverflow.com/questions/13429451/why-is-9999999999999999-converted-to-10000000000000000-in-javascript).

If the value is stored as a number, there's nothing to do. If the value is stored as a string, we might be able to work around this problem, but that would mean a good amount of work.

Have you found this bug under a real world scenario? Or was it just by messing around with the documentation?

**Comment by druchoy** [comment]
Ah. Thanks for the response.

yah, was hoping to use as a string as a work around too.

I was thinking about using the lib to handle a field with number of bytes. So the numbers get large fast.

**Comment by zcilohlegna** [comment]
Actually this is a real case for Indonesian, since 11 digits of number is representing billions which is pretty common for a product to have such price. But I wonder, why there are only 10 digits precision in redux-form-input-masks, whereas there are actually 16 digits precision on Java Script?
