### ISSUE TITLE
NumberMask format does not handle null value

### ISSUE THREAD

**Issue by neprev** [renato-bohler/redux-form-input-masks#64]
### What are you reporting?

* [x] Feature request

### What is the current behavior?

Despite the fact that allowEmpty is set to true, the mask is displayed if value === null, because of this https://github.com/renato-bohler/redux-form-input-masks/blob/master/src/createNumberMask.js#L40

### What is the expected behavior?

Do not display the mask if value === null

**Comment by renato-bohler** [comment]
Hey, thanks for creating this issue.

I believe that this is going to be solved by #37.

I'll try to solve it in the next few days or so.
