### ISSUE TITLE
How to create variable length text masks?

### ISSUE THREAD

**Issue by taschetto** [renato-bohler/redux-form-input-masks#68]
### What are you reporting?

* [ ] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [X] Other (describe)

### Help wanted

Is it possible to create a variable length text mask, such as an email? Something like this...

```
const emailMask = createTextMask({
  pattern: 'R@mydomain.com',
  guide: true,
  maskDefinitions: {
    R: {
      regExp: /[a-z0-9.]+/,
    },
  },
})
```

**Comment by renato-bohler** [comment]
Hmm, unfortunately, variable length text masks aren't fully supported yet.

I would have to take some time and study the possibility of accepting a function on the `pattern` key. Something like that:

````js
const emailMask = createTextMask({
  pattern: (value) => `${Array.from(value || '').fill('R').join('')}@mydomain.com`,
  guide: true,
  maskDefinitions: {
    R: {
      regExp: /[a-z0-9.]+/,
    },
  },
})
```

But even then, I'm not totally sure that this would work as expected. I'll try to figure it out on the next couple of weeks.

**Comment by renato-bohler** [comment]
[Here's a way to hack in variable length text masks right now](https://codesandbox.io/s/zll3xn8wmx):

```js
const getTelephonePattern = (telephone = "") => {
  if (telephone.length === 11) {
    return "(99) 9 9999-9999";
  } else if (telephone.length > 8) {
    return "(99) 9999-9999 9";
  }
  return "9999-9999 9";
};

// ...

<Field
  name="telephone"
  component="input"
  type="tel"
  {...createTextMask({
    pattern: getTelephonePattern(props.inputValues.telephone),
    guide: false,
    allowEmpty: true
  })}
/>
```

This [codesandbox link](https://codesandbox.io/s/zll3xn8wmx) has the example above implemented, as well as your use case, which doesn't work quite well.

The problem with this e-mail mask is that there are characters on the `guide` that matches a pattern on `maskDefinitions`. So when you type in a character that matches these requirements (like `m`, `y`, `d`, `o`, etc.), the input value loses itself and shuffles somehow.
