### ISSUE TITLE
Codesanbox examples are broken

### ISSUE THREAD

**Issue by mkarajohn** [renato-bohler/redux-form-input-masks#71]
### What are you reporting?

* [ ] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [x] Other (describe)

### What is the current behavior?

Codesanbox examples, from the documentation, are broken, with error 
```
TypeError
_react.default.createContext is not a function
```

[Example 1](https://codesandbox.io/s/k0op1kwywr)
[Example 2](https://codesandbox.io/s/9o5vyqxn84)

**Comment by cosmosdesigner** [comment]
Hi @mkarajohn this is a working sandbox with TS: https://codesandbox.io/s/zl27211yyx
