### ISSUE TITLE
Typescript error when updating from 1.3 to latest

### ISSUE THREAD

**Issue by cosmosdesigner** [renato-bohler/redux-form-input-masks#73]
### What are you reporting?

* [x ] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

ERROR: (alias) class Field<P = InputHTMLAttributes<HTMLInputElement> | SelectHTMLAttributes<HTMLSelectElement> | TextareaHTMLAttributes<HTMLTextAreaElement> | BaseFieldProps<{}>>
import Field
Type '{ format: (storeValue: ReactText) => string; normalize: (updatedValue: string, previousValue: ReactText) => ReactText; onChange: (event: Event) => void; onFocus: (event: Event) => void; autoComplete: string; name: "number"; component: "input"; type: string; }' is not assignable to type 'Readonly<BaseFieldProps<{ format: (storeValue: ReactText) => string; normalize: (updatedValue: string, previousValue: ReactText) => ReactText; onChange: (event: Event) => void; onFocus: (event: Event) => void; autoComplete: string; name: "number"; component: "input"; type: string; }> & { ...; }>'.
 Types of property 'onChange' are incompatible.
   Type '(event: Event) => void' is not assignable to type 'EventWithDataHandler<ChangeEvent<any>> & ((event: Event) => void)'.
     Type '(event: Event) => void' is not assignable to type 'EventWithDataHandler<ChangeEvent<any>>'.
       Types of parameters 'event' and 'event' are incompatible.
         Type 'ChangeEvent<any>' is missing the following properties from type 'Event': cancelBubble, composed, returnValue, srcElement, and 7 more.

### What is the expected behavior?
Not having this error

### Sandbox Link

https://zl27211yyx.codesandbox.io/

https://codesandbox.io/s/zl27211yyx

on userForm.tsx file

Thank you :)

**Comment by jcspader** [comment]
The same problem here.

`
    "react": "^16.8.6",
    "redux": "^4.0.1",
    "redux-form": "^8.1.0",
    "redux-form-input-masks": "^2.0.1",
`

**Comment by renato-bohler** [comment]
Fixed by https://github.com/renato-bohler/redux-form-input-masks/pull/127
