### ISSUE TITLE
It does not work with Reduxform 8.1.0

### ISSUE THREAD

**Issue by JoeyKou** [renato-bohler/redux-form-input-masks#74]
It took me several hours to figure it out. The latest version it supports is 7.4.2. If you switch to 8.1.0, it won't be able to enter data.

**Comment by taschetto** [comment]
I'm using

```json
    "redux-form": "^8.1.0",
    "redux-form-input-masks": "^1.3.0",
```

without any problem...

**Comment by paulanelo** [comment]
@taschetto do you have an example? I'm trying to use
`    "redux-form": "^8.2.2",
    "redux-form-input-masks": "^2.0.1",
`
but it doesn't works and if I change to your recommendation still doesn't works here. Example: https://codesandbox.io/embed/redux-form-antd-ls2lc

**Comment by taschetto** [comment]
Hi, @paulanelo. Here's an excerpt from my `package.json`.

```json
{
  "dependencies": {
    "classnames": "^2.2.6",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-dom": "^16.6.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.1",
    "redux-form": "^8.1.0",
    "redux-form-input-masks": "^1.3.0",
    "yarn": "^1.17.3"
  }
}```

**Comment by paulanelo** [comment]
Hello, @taschetto now is working. Thank you!

**Comment by taschetto** [comment]
Nice! :)
